$(document).ready(function(){
    $('.slider-area').owlCarousel({
        items:1,
        loop:true,
        nav:false,
        autoplay:false,
        dots:true
    })
       $('.logo-carousel').owlCarousel({
        items:5,
        loop:true,
        nav:false,
        autoplay:false,
    })
})